# Default versions of tools, to update these, set [tools.override]
[tools]
dprint = "latest"
golang = "1.25.5"
golangci-lint = "2.8.0"
goreleaser = "latest"
gotestsum = "1.13.0"
"go:golang.org/x/tools/cmd/goimports" = "latest"
shfmt = "latest"

[tasks.fmt]
alias = "format"
description = "Format code"
run = ["go mod tidy", "gofmt -s -w .", "goimports -w .", "shfmt -w ."]

[tasks.lint]
description = "Run linters"
run = "golangci-lint run"

[tasks.test]
description = "Run tests"
run = "gotestsum"

## <<Stencil::Block(custom)>>
[tasks.ci-local]
run = [
	"gh act --platform ubuntu-latest=ghcr.io/catthehacker/ubuntu:full-24.04 --job test-action --secret GITHUB_TOKEN=$(gh auth token)",
]
## <</Stencil::Block>>
